language: ruby

rvm:
  - 2.3
  - 2.6

before_install:
  - gem install bundler -v 2.0.1 --no-document

script:
  - bundler exec ruby tests/tc_all.rb

notifications:
  email:
    - chitimba@wavefront.com
